/**
 * This class is generated by jOOQ
 */
package com.conanli.job.jooq_generated;


import com.conanli.job.jooq_generated.tables.Contact;
import com.conanli.job.jooq_generated.tables.Job;
import com.conanli.job.jooq_generated.tables.JobHistory;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -1798759883;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * 联系人
     */
    public final Contact CONTACT = Contact.CONTACT;

    /**
     * 定时任务
     */
    public final Job JOB = Job.JOB;

    /**
     * 任务执行记录
     */
    public final JobHistory JOB_HISTORY = JobHistory.JOB_HISTORY;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Contact.CONTACT,
            Job.JOB,
            JobHistory.JOB_HISTORY);
    }
}
