/**
 * This class is generated by jOOQ
 */
package com.conanli.job.jooq_generated;


import com.conanli.job.jooq_generated.tables.Contact;
import com.conanli.job.jooq_generated.tables.Job;
import com.conanli.job.jooq_generated.tables.JobHistory;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 联系人
     */
    public static final Contact CONTACT = Contact.CONTACT;

    /**
     * 定时任务
     */
    public static final Job JOB = Job.JOB;

    /**
     * 任务执行记录
     */
    public static final JobHistory JOB_HISTORY = JobHistory.JOB_HISTORY;
}
